Fix/expandable carousel options
nixrajput/flutter_carousel_widget pull request #53
Opened 2024-09-03 08:57 UTC by aferret0

The goal of this PR is to make ExpandableCarousel backwards compatible (issue https://github.com/nixrajput/flutter_carousel_widget/issues/51)

I had some issues which pop off during my development (hide CarouselController and WidgetStateProperty), I fixed them for me but if it was not necessary I can remove it.

2024-09-04 06:59 UTC, nixrajput commented
Hi @aferret0,

Thank you for the PR.

Can you help me to understand why did you remove hide CarouselController from 'material.dart' imports?
It was causing issue in prior update due to a CarouselController with same class name provided in material.dart.

2024-09-04 07:20 UTC, nixrajput commented
I think we should create a base class for CarouselOptions, CarouselState, and CarouselController and then extends them accordingly to achieve backward compatibility. This will ensure the stability in our future updates too.

2024-09-04 07:21 UTC, nixrajput requested changes
https://github.com/nixrajput/flutter_carousel_widget/pull/53#issuecomment-2328103396

2024-09-06 15:29 UTC, aferret0 commented
I had a newer version of Flutter and forget about CarouselController was removed from it.
I'm gonna remove these modifications and take actions about your review

2024-09-08 13:53 UTC, closed without merging